"""initial_schema

Revision ID: 60e25659f63e
Revises: 
Create Date: 2026-05-02 20:04:13.407406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e25659f63e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatars',
    sa.Column('avatar_id', sa.String(length=64), nullable=False),
    sa.Column('visual_prompt', sa.Text(), nullable=False),
    sa.Column('motion_prompt', sa.Text(), nullable=False),
    sa.Column('caption_template', sa.Text(), nullable=False),
    sa.Column('hashtag_set', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('avatar_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('avatar_id', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('input_image_url', sa.Text(), nullable=True),
    sa.Column('generated_image_url', sa.Text(), nullable=True),
    sa.Column('model_3d_url', sa.Text(), nullable=True),
    sa.Column('model_3d_task_id', sa.String(length=128), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('use_3d', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('avatars')
    # ### end Alembic commands ###
